version: '3.7'

services:

  db:
    image: postgres:12.0-alpine
    env_file:
      - db/db.env
    networks:
      - db_network
    volumes:
        - db_volume:/var/lib/postgresql/data

  api:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - src/app.env
    volumes:
      - ./src/:/usr/src/
    networks:
      - db_network
      - nginx_network
    depends_on:
      - db
    links:
      - db:db

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
  static_volume:
  media_volume: